#!/bin/sh

# Script taken from Mandriva Package
# Modified for Slackware by Heinz Wiesinger <HMWiesinger@gmx.at>

if [ "$BROWSER" = "" ]; then
  BROWSER=${BROWSER:-firefox}
fi

url='http://localhost/phpMyAdmin'
if ! [ -z "$BROWSER" ] && ( which $BROWSER ); then
  browser=`which $BROWSER`
elif [ -x /usr/bin/firefox ]; then
  browser=/usr/bin/firefox
elif [ -x /usr/bin/konqueror ]; then
  browser=/usr/bin/konqueror
elif [ -x /usr/bin/seamonkey ]; then
  browser=/usr/bin/seamonkey
elif [ -x /usr/bin/opera ]; then
  browser=/usr/bin/opera
elif [ -x /usr/bin/lynx ]; then
  browser='xterm -bg black -fg white -e lynx'
elif [ -x /usr/bin/links ]; then
  browser='xterm -bg black -fg white -e links'
else
  echo "No web browser found, install one, set the BROWSER environment variable"
  echo "or call the script with 'BROWSER=yourBrowserHere phpMyAdmin'"
  exit 1
fi
$browser $url
